### ISSUE TITLE
treehouse update fails

### ISSUE THREAD

**Issue by markgene** [ropensci/UCSCXenaTools#26] opened 2020-06-25 15:01 UTC
Hi Shixiang, 

Thank you for developing the package! It is very easy to use. However, I failed to update the dataset of treehouse. See below.
Thanks!

```{r}
> packageVersion("UCSCXenaTools")
[1] ‘1.3.1’
> XenaDataUpdate()
=> Obtaining info from UCSC Xena hubs...
==> Searching cohorts for host https://ucscpublic.xenahubs.net...
==> Trying #1
===> #37 cohorts found.
===> Querying datasets info...
===> #114 datasets found.
...
==> Searching cohorts for host https://xena.treehouse.gi.ucsc.edu...
==> Trying #1
==> Trying #2
==> Trying #3
Error in value[[3L]](cond) : 
  Tried 3 times but failed, please check URL or your internet connection!
```

**Comment by ShixiangWang** [comment] 2020-06-27 15:29
@markgene Thanks for reporting, this isssue is typically calused by your unstable internet connection. I will try to update the datasets and push a new version.

**Comment by ShixiangWang** [comment] 2020-06-27 15:36
@markgene Based on <https://xenabrowser.net/hub/>, the problem is that the hub is down, so we cannot connect it from R 

![image](https://user-images.githubusercontent.com/25057508/85926033-0cc1f400-b8cf-11ea-87c0-cb62459c66d9.png)

**Comment by ShixiangWang** [comment] 2020-06-27 15:38
You can send an email to Xena team to check the server problem, I cannot help you out from this. I am closing this issue now, feel free to reopen it.

**Closed as completed by ShixiangWang** 2020-06-27 15:38 UTC
Labels: data-source-update
